name: "update wiki"

# Run on changes to the `doc` directory on the `master` branch
on:
  push:
    branches:
      - master
    paths:
      - 'doc/**'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          path: workflow-practice
      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: "captcardoso/workflow-practice.wiki"
          path: workflow-practice.wiki
      - name: Copy files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Wiki mirror"
          cp $GITHUB_WORKSPACE/workflow-practice/doc/*.txt $GITHUB_WORKSPACE/workflow-practice.wiki
          cd $GITHUB_WORKSPACE/workflow-practice.wiki rename.ul -v .txt .md *.txt
          git add .
          # only commit if there are changes
          git diff-index --quiet HEAD -- || git commit -m "sync from doc/"
          git push